services:
  - postgresql

language: node_js

node_js:
  - 13

install:
  - npm install

before_script:
  - psql -c 'create datatabase travis_ci_test;' -U postgres
  - export CI_DATABASE_ENDPOINT=postgres://postgres:@postgresql/travis_ci_test

script:
  - npm run lint
  - npm run test

