version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:1.1.6
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test_db
    environment:
      NODE_ENV: test
      CI_DATABASE_URL: localhost
      CI_DATABASE_USERNAME: root
      CI_DATABASE_NAME: test_db
      CI_DATABASE_ENDPOINT: postgres://root@localhost/test_db
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run db:migrate
            - run: npm run db:seed:all
            - run: npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-test
