---
- hosts: sprofile-instance
  remote_user: root

  vars:
    project_directory: '/home/sprofile/repo/sprofile-page'

  roles:
    - docker

  tasks:
  - name: Add sprofile group
    group:
      name: sprofile
      gid: 999
      state: present

  - name: Add sprofile user
    user:
      name: sprofile
      shell: /bin/bash
      uid: 999
      groups: sprofile,docker

  - name: git clone the project
    become: yes
    become_user: sprofile
    git:
      repo: 'https://github.com/stvnorg/sprofile-page.git'
      dest: "{{ project_directory }}"

  - name: Deploy the app (docker-compose)
    shell: docker-compose up -d
    args:
      chdir: "{{ project_directory }}"
